version: '3.8'  # Always good to specify the version

services:
  write-service:
    build: encoder
    ports:
      - "8081:8080"
    depends_on:
      cassandra-db:
        condition: service_healthy
      broker:
        condition: service_healthy
    
  read-service:
    build: decoder
    ports:
      - "8082:8080"
    depends_on:
      cassandra-db:
        condition: service_healthy

  remover-service:
    build: remover
    depends_on:
      cassandra-db:
        condition: service_healthy

  cassandra-db:
    image: cassandra:latest
    container_name: cassandra-db
    hostname: cassandra-db
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_SEEDS: "cassandra-db"
      CASSANDRA_CLUSTER_NAME: SolarSystem
      CASSANDRA_DC: Mars
      CASSANDRA_RACK: West
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    volumes:
      - cassandra-data:/var/lib/cassandra               # Using a named volume
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - '19092:19092'
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1" ]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 5

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:19092,PLAINTEXT://broker:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:9093'
      KAFKA_LISTENERS: 'CONTROLLER://:9093,PLAINTEXT_HOST://:19092,PLAINTEXT://:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

volumes:  # This should be at the same level as 'services'
  cassandra-data:
    driver: local  # Optional: specifying the driver, default is 'local'


